[package]
name = "modular-bitfield-to-value"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
proc-macro = true

[dependencies]
modular-bitfield = "0.11.2"
proc-macro2 = "1.0"
quote = "1.0"
syn = "1.0"
